# Generated by Django 2.1 on 2018-12-11 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('matricula', models.CharField(max_length=7, verbose_name='Matrícula')),
                ('imagen', models.TextField(verbose_name='Img')),
                ('imagen_mini', models.TextField(verbose_name='Img (min)')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregada', models.BooleanField(verbose_name='Entregada')),
                ('alcanzado', models.BooleanField(verbose_name='Alcanzado')),
                ('atendida', models.BooleanField(verbose_name='Atendida')),
                ('fecha_entregada', models.DateTimeField(null=True, verbose_name='Fecha Entregada')),
                ('fecha_atendida', models.DateTimeField(null=True, verbose_name='Fecha Atendida')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Alerta', verbose_name='Alerta')),
            ],
            options={
                'ordering': ['-alerta'],
            },
        ),
        migrations.CreateModel(
            name='Patrullero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Peaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='notificado',
            name='patrullero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patrullero', verbose_name='Patrullero'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='peaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Peaje', verbose_name='Peaje'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='notificados',
            field=models.ManyToManyField(through='core.Notificado', to='core.Patrullero'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='peaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Peaje', verbose_name='Peaje'),
        ),
    ]
