# Generated by Django 2.1 on 2018-12-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181211_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matricula_Solicitada',
            new_name='MatriculaSolicitada',
        ),
    ]
