# Generated by Django 2.1 on 2018-12-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181211_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculasolicitada',
            options={'ordering': ['-fecha_solicitada'], 'verbose_name_plural': 'Matrículas Solicitadas'},
        ),
        migrations.RemoveField(
            model_name='peaje',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='patrullero',
            name='mac',
            field=models.CharField(default=0, max_length=100, verbose_name='Mac'),
            preserve_default=False,
        ),
    ]
