# Generated by Django 2.1 on 2018-12-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181211_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='matricula',
            field=models.CharField(default=123456, max_length=7, verbose_name='Matrícula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificado',
            name='alcanzado',
            field=models.BooleanField(default=False, verbose_name='Alcanzado'),
        ),
        migrations.AlterField(
            model_name='notificado',
            name='atendida',
            field=models.BooleanField(default=False, verbose_name='Atendida'),
        ),
        migrations.AlterField(
            model_name='notificado',
            name='entregada',
            field=models.BooleanField(default=False, verbose_name='Entregada'),
        ),
    ]
