# Generated by Django 2.1 on 2018-12-12 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181211_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='peaje',
        ),
        migrations.AddField(
            model_name='alerta',
            name='lectura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Lectura', verbose_name='Lectura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectura',
            name='direccion',
            field=models.CharField(default='POZ', max_length=50, verbose_name='Dirección'),
            preserve_default=False,
        ),
    ]
