# Generated by Django 2.1 on 2018-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181212_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrullero',
            name='mac',
        ),
        migrations.AddField(
            model_name='patrullero',
            name='cedula',
            field=models.CharField(default=123456, max_length=10, verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrullero',
            name='token',
            field=models.CharField(default=123456, max_length=250, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
