# Generated by Django 2.1 on 2018-12-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181214_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificado',
            name='fecha_atendida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Atendida'),
        ),
        migrations.AlterField(
            model_name='notificado',
            name='fecha_entregada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entregada'),
        ),
    ]
