# Generated by Django 2.1 on 2018-12-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181219_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaje',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Puede conocer la latitud en Google Maps; Click Derecho -> ¿Qué hay aquí?', max_digits=9, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peaje',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Puede conocer la latitud en Google Maps; Click Derecho -> ¿Qué hay aquí?', max_digits=9, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peaje',
            name='radio',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Indique el radio (en metros) de acción para el envío de notificaciones', max_digits=10),
            preserve_default=False,
        ),
    ]
