# Generated by Django 2.1 on 2019-01-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181221_0155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificado',
            new_name='Notificacion',
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-alerta'], 'verbose_name': 'notificación', 'verbose_name_plural': 'notificaciones'},
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='notificados',
        ),
        migrations.AddField(
            model_name='alerta',
            name='notificaciones',
            field=models.ManyToManyField(through='core.Notificacion', to='core.Patrullero'),
        ),
        migrations.AlterField(
            model_name='peaje',
            name='longitud',
            field=models.DecimalField(decimal_places=6, help_text='Puede conocer la longitud en Google Maps; Click Derecho -> ¿Qué hay aquí?', max_digits=9, verbose_name='Longitud'),
        ),
    ]
