# Generated by Django 2.1 on 2019-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190113_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='video',
            field=models.CharField(default='null.avi', max_length=255, verbose_name='Video'),
            preserve_default=False,
        ),
    ]
